### ISSUE TITLE
SQL errors don't go away

### ISSUE THREAD

**Issue by pnorman** [stamen/atom-cartodb#19]
If I go to a zoom with a SQL error then zoom back out to a zoom which works, the SQL error is still displayed.

**Comment by sethfitz** [comment]
Partially intentional (so that the error can be tracked / resolved), but a better implementation would probably be to log it in a file local to the project and allow it to disappear.

Saving any of the YAML or MSS files will trigger a refresh and make it go away in the meantime.

**Comment by pnorman** [comment]
Is there a way to trigger a refresh when no changes have been made to the files?

**Comment by sethfitz** [comment]
`@cachebuster` (https://github.com/CartoDB/CartoDB-basemaps/blob/develop/styles/global_variables.mss#L5) exists for this purpose. Brandon was using it while iterating on functions + data sources.
